#!/usr/bin/env bash
set -euo pipefail

target="${1:-$HOME/.config/hypr/hyprland.conf}"
script_path="$(readlink -f -- "${BASH_SOURCE[0]}")"
script_dir="$(cd -- "$(dirname -- "$script_path")" && pwd)"
repo_root="$(cd -- "$script_dir/../.." && pwd)"
expected_source="source = \$RepoRoot/common/hyprland.conf"

repair_config() {
  local target_path="$1"
  local target_dir=""
  local backup=""

  target_dir="$(dirname -- "$target_path")"
  mkdir -p "$target_dir"

  if [[ -e "$target_path" || -L "$target_path" ]]; then
    backup="$target_dir/hyprland.conf.replaced.$(date +%Y%m%d%H%M%S)"
    mv -f -- "$target_path" "$backup"
    printf 'Backed up replaced Hyprland entry point to %s\n' "$backup"
  fi

  cat > "$target_path" <<EOF
# Local entry point for the generated active profile.
\$RepoRoot = $repo_root
$expected_source
EOF
  chmod 0644 "$target_path"
  printf 'Restored Hyprland entry point at %s\n' "$target_path"
}

if [[ ! -f "$target" ]]; then
  repair_config "$target"
  exit 0
fi

if grep -q '^autogenerated[[:space:]]*=[[:space:]]*1' "$target"; then
  repair_config "$target"
  exit 0
fi

repo_root_line="$(grep -E '^\$RepoRoot = ' "$target" | tail -n 1 || true)"
repo_root_value="${repo_root_line#\$RepoRoot = }"

case "$repo_root_value" in
  /*)
    if [[ -f "$repo_root_value/common/hyprland.conf" ]]; then
      repo_root_ok=1
    else
      repo_root_ok=0
    fi
    ;;
  *)
    repo_root_ok=0
    ;;
esac

if [[ "$repo_root_ok" -ne 1 ]] || ! grep -qxF "$expected_source" "$target"; then
  printf 'Hyprland entry point is not the managed wrapper: %s\n' "$target" >&2
  exit 1
fi

printf 'Hyprland entry point is managed and intact: %s\n' "$target"
