#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: set-hypr-profile.sh [--profile laptop|desktop] [--symlink] [--install-guard] [--configure-faillock] [--dry-run] [--force]

Detects the machine type and writes HYPR_PROFILE to:
  ~/.config/environment.d/99-hypr.conf
Also updates UserConfigs/Host.conf to point at the active profile.
Builds a local active/ tree that combines the shared common/ base with
machine-local runtime files. By default it symlinks ~/.config/hypr to that
active tree and installs the Hyprland config guard.
It leaves system PAM settings alone by default. The optional
--configure-faillock explicitly weakens system authentication lockouts.

Options:
  --profile    Force a profile ("laptop" or "desktop"); omit for auto-detect
  --symlink    Symlink ~/.config/hypr to the detected profile (default)
  --install-guard
               Install a systemd user path that repairs Hyprland's autogenerated stub (default)
  --configure-faillock
               SECURITY RISK: opt in to weakening /etc/security/faillock.conf.
               Root/sudo is required; a backup is created. Prefer fixing PAM/Hyprlock.
  --skip-faillock
               Legacy no-op: PAM is already untouched by default
  --dry-run    Print what would change without writing files
  --force      Kept for compatibility; setup already backs up replaced paths
EOF
}

profile=""
dry_run=0
force=0
do_symlink=1
install_guard=1
configure_faillock=0
apply_faillock_only=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      profile="${2:-}"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    --symlink)
      do_symlink=1
      shift
      ;;
    --install-guard)
      install_guard=1
      shift
      ;;
    --configure-faillock)
      configure_faillock=1
      ;;
    --skip-faillock)
      configure_faillock=0
      shift
      ;;
    --apply-faillock-only)
      apply_faillock_only=1
      shift
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

detect_profile() {
  local chassis=""
  local chassis_type=""
  if command -v hostnamectl >/dev/null 2>&1; then
    chassis="$(hostnamectl chassis 2>/dev/null || true)"
    case "$chassis" in
      laptop|desktop)
        echo "$chassis"
        return 0
        ;;
    esac
  fi

  if [[ -r /sys/class/dmi/id/chassis_type ]]; then
    chassis_type="$(tr -d '[:space:]' </sys/class/dmi/id/chassis_type)"
    case "$chassis_type" in
      8|9|10|11|14)
        echo "laptop"
        return 0
        ;;
      3|4|5|6|7|13|15|16|35|36)
        echo "desktop"
        return 0
        ;;
    esac
  fi

  if compgen -G "/sys/class/power_supply/BAT*" >/dev/null; then
    echo "laptop"
  else
    echo "desktop"
  fi
}

if [[ -z "$profile" ]]; then
  profile="$(detect_profile)"
fi

if [[ "$profile" != "laptop" && "$profile" != "desktop" ]]; then
  echo "Invalid profile: $profile" >&2
  exit 1
fi

env_dir="$HOME/.config/environment.d"
env_file="$env_dir/99-hypr.conf"
new_line="HYPR_PROFILE=$profile"
repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
script_path="$repo_root/$(basename -- "${BASH_SOURCE[0]}")"
profile_dir="$repo_root/$profile"
active_dir="$repo_root/active"
legacy_host_conf="$profile_dir/UserConfigs/Host.conf"
active_userconfigs_dir="$active_dir/UserConfigs"
active_host_conf="$active_userconfigs_dir/Host.conf"
guard_service_name="hypr-config-guard.service"
guard_path_name="hypr-config-guard.path"
graphical_session_service_name="hypr-graphical-session.service"

backup_existing_path() {
  local path="$1"
  [[ -e "$path" || -L "$path" ]] || return 0
  local backup="${path}.bak.$(date +%Y%m%d%H%M%S)"
  local stem="$backup" counter=1
  while [[ -e "$backup" || -L "$backup" ]]; do
    backup="${stem}.${counter}"
    ((counter += 1))
  done
  mv -- "$path" "$backup"
  printf 'Backed up %s to %s\n' "$path" "$backup"
}

install_faillock_config() {
  local target=/etc/security/faillock.conf
  local start_marker="# BEGIN managed by hyprland repo: disable faillock lockout"
  local end_marker="# END managed by hyprland repo: disable faillock lockout"
  local backup=""

  if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    if command -v sudo >/dev/null 2>&1; then
      sudo -- "$script_path" --apply-faillock-only
      return
    fi

    echo "sudo is required to update $target" >&2
    return 1
  fi

  mkdir -p "$(dirname "$target")"
  touch "$target"

  backup="${target}.bak.$(date +%Y%m%d%H%M%S)"
  local stem="$backup" counter=1
  while [[ -e "$backup" || -L "$backup" ]]; do
    backup="${stem}.${counter}"
    ((counter += 1))
  done
  cp -a "$target" "$backup"

  sed -i -E 's/^([[:space:]]*)(deny|fail_interval|unlock_time)([[:space:]=].*)$/# disabled by hyprland repo: \2\3/' "$target"
  sed -i "/^${start_marker}$/,/^${end_marker}$/d" "$target"

  {
    printf '\n%s\n' "$start_marker"
    printf '# Effectively disables local PAM faillock lockouts for failed unlock attempts.\n'
    printf 'deny = 999999\n'
    printf 'fail_interval = 1\n'
    printf 'nodelay\n'
    printf '%s\n' "$end_marker"
  } >>"$target"

  if command -v faillock >/dev/null 2>&1; then
    faillock --reset || true
  fi

  echo "Updated $target"
  echo "Backed up previous faillock config to $backup"
}

if [[ $apply_faillock_only -eq 1 ]]; then
  install_faillock_config
  exit 0
fi

link_managed_path() {
  local target="$1"
  local link_path="$2"

  rm -rf "$link_path"
  ln -s "$target" "$link_path"
}

write_host_conf() {
  local host_conf="$1"

  mkdir -p "$(dirname "$host_conf")"
  rm -f "$host_conf"
  cat > "$host_conf" <<EOF
# Host profile selector (local to this machine).
# set-hypr-profile.sh rewrites this file to point at the active profile.
\$RepoRoot = $repo_root
source = \$RepoRoot/profiles/$profile.conf
EOF
}

write_hyprland_entrypoint() {
  local target_path="$1"

  rm -f "$target_path"
  cat > "$target_path" <<EOF
# Local entry point for the generated active profile.
\$RepoRoot = $repo_root
source = \$RepoRoot/common/hyprland.conf
EOF
}

write_wallust_fallback() {
  local target_path="$1"

  rm -f "$target_path"
  cat > "$target_path" <<'EOF'
# Generated fallback colors. Wallust may overwrite this file.
$background = rgb(1e1e2e)
$foreground = rgb(cdd6f4)
$color0 = rgb(1e1e2e)
$color1 = rgb(f38ba8)
$color2 = rgb(a6e3a1)
$color3 = rgb(f9e2af)
$color4 = rgb(89b4fa)
$color5 = rgb(cba6f7)
$color6 = rgb(94e2d5)
$color7 = rgb(bac2de)
$color8 = rgb(45475a)
$color9 = rgb(f38ba8)
$color10 = rgb(a6e3a1)
$color11 = rgb(f9e2af)
$color12 = rgb(89b4fa)
$color13 = rgb(cba6f7)
$color14 = rgb(94e2d5)
$color15 = rgb(cdd6f4)
EOF
}

install_systemd_guard() {
  local systemd_user_dir="$HOME/.config/systemd/user"
  local guard_script="%h/.config/hypr/scripts/GuardHyprConfig.sh"
  local local_guard_script="$HOME/.config/hypr/scripts/GuardHyprConfig.sh"

  mkdir -p "$systemd_user_dir"
  backup_existing_path "$systemd_user_dir/$guard_service_name"
  backup_existing_path "$systemd_user_dir/$guard_path_name"
  backup_existing_path "$systemd_user_dir/$graphical_session_service_name"

  cat > "$systemd_user_dir/$guard_service_name" <<EOF
[Unit]
Description=Repair Hyprland config entry point if it is replaced by the autogenerated stub

[Service]
Type=oneshot
ExecStart=$guard_script
EOF

  cat > "$systemd_user_dir/$guard_path_name" <<EOF
[Unit]
Description=Watch Hyprland config entry point for unexpected replacement

[Path]
PathChanged=%h/.config/hypr/hyprland.conf
Unit=$guard_service_name

[Install]
WantedBy=default.target
EOF

  cat > "$systemd_user_dir/$graphical_session_service_name" <<'EOF'
[Unit]
Description=Connect a direct Hyprland launch to graphical-session.target
Wants=graphical-session.target
After=graphical-session-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/true
EOF

  systemctl --user daemon-reload
  systemctl --user enable --now "$guard_path_name"
  "$local_guard_script"
}

build_active_tree() {
  local rel=""
  local source_path=""
  local target_path=""
  local name=""

  mkdir -p "$active_dir" "$active_userconfigs_dir" \
    "$active_dir/wallpaper_effects" "$active_dir/wallust"

  for rel in \
    Monitor_Profiles \
    animations \
    configs \
    scripts \
    application-style.conf \
    hypridle.conf \
    hyprlock-2k.conf \
    hyprlock.conf \
    initial-boot.sh \
    v2.3.20
  do
    source_path="$repo_root/common/$rel"
    target_path="$active_dir/$rel"
    link_managed_path "$source_path" "$target_path"
  done

  write_hyprland_entrypoint "$active_dir/hyprland.conf"

  rm -rf "$active_dir/UserScripts"
  mkdir -p "$active_dir/UserScripts"
  for source_path in "$repo_root/common/UserScripts/"*; do
    [[ -e "$source_path" ]] || continue
    link_managed_path "$source_path" "$active_dir/UserScripts/$(basename "$source_path")"
  done

  for source_path in "$profile_dir/UserScripts/"*; do
    [[ -e "$source_path" ]] || continue
    name="$(basename "$source_path")"
    if [[ ! -e "$repo_root/common/UserScripts/$name" || "$name" == "WallpaperAutoChange.sh" || "$name" == "WallpaperRandom.sh" ]]; then
      link_managed_path "$source_path" "$active_dir/UserScripts/$name"
    fi
  done

  for source_path in "$repo_root/common/UserConfigs/"*; do
    [[ -e "$source_path" ]] || continue
    link_managed_path "$source_path" "$active_userconfigs_dir/$(basename "$source_path")"
  done

  if [[ -f "$profile_dir/UserConfigs/Host.conf.example" ]]; then
    link_managed_path \
      "$profile_dir/UserConfigs/Host.conf.example" \
      "$active_userconfigs_dir/Host.conf.example"
  fi

  write_host_conf "$active_host_conf"

  if [[ ! -e "$active_dir/monitors.conf" && -f "$profile_dir/monitors.conf" ]]; then
    cp "$profile_dir/monitors.conf" "$active_dir/monitors.conf"
  fi

  if [[ ! -e "$active_dir/workspaces.conf" && -f "$profile_dir/workspaces.conf" ]]; then
    cp "$profile_dir/workspaces.conf" "$active_dir/workspaces.conf"
  fi

  if [[ ! -e "$active_dir/monitors.conf" ]]; then
    printf '# Local monitor layout overrides.\n' > "$active_dir/monitors.conf"
  fi

  if [[ ! -e "$active_dir/workspaces.conf" ]]; then
    printf '# Local workspace rules.\n' > "$active_dir/workspaces.conf"
  fi

  if [[ ! -e "$active_dir/wallpaper_effects/.wallpaper_current" && -f "$profile_dir/wallpaper_effects/.wallpaper_current" ]]; then
    cp "$profile_dir/wallpaper_effects/.wallpaper_current" "$active_dir/wallpaper_effects/.wallpaper_current"
  fi

  if [[ ! -e "$active_dir/wallust/wallust-hyprland.conf" && -f "$profile_dir/wallust/wallust-hyprland.conf" ]]; then
    cp "$profile_dir/wallust/wallust-hyprland.conf" "$active_dir/wallust/wallust-hyprland.conf"
  fi

  if [[ ! -e "$active_dir/wallust/wallust-hyprland.conf" ]]; then
    write_wallust_fallback "$active_dir/wallust/wallust-hyprland.conf"
  fi
}

if [[ $dry_run -eq 1 ]]; then
  echo "Would write: $env_file"
  echo "$new_line"
  echo "Would build: $active_dir"
  echo "Would write: $active_host_conf"
  echo "source = $repo_root/profiles/$profile.conf"
  echo "Would write: $legacy_host_conf"
  echo "source = $repo_root/profiles/$profile.conf"
  if [[ $do_symlink -eq 1 ]]; then
    echo "Would symlink: $HOME/.config/hypr -> $active_dir"
  fi
  if [[ $install_guard -eq 1 ]]; then
    echo "Would install and enable: $guard_path_name"
  fi
  if [[ $configure_faillock -eq 1 ]]; then
    echo "Would update: /etc/security/faillock.conf"
  fi
  exit 0
fi

mkdir -p "$env_dir"

if [[ -f "$env_file" && ! -L "$env_file" && "$(cat "$env_file")" == "$new_line" ]]; then
  echo "HYPR_PROFILE already set to '$profile' in $env_file"
else
  backup_existing_path "$env_file"
  printf '%s\n' "$new_line" > "$env_file"
  echo "Set HYPR_PROFILE=$profile in $env_file"
fi

if [[ ! -d "$profile_dir/UserConfigs" ]]; then
  echo "UserConfigs directory not found: $profile_dir/UserConfigs" >&2
  exit 1
fi

build_active_tree
echo "Built $active_dir"

write_host_conf "$legacy_host_conf"
echo "Wrote $legacy_host_conf"
echo "Wrote $active_host_conf"

if [[ $do_symlink -eq 1 ]]; then
  if [[ ! -d "$active_dir" ]]; then
    echo "Active directory not found: $active_dir" >&2
    exit 1
  fi

  hypr_dir="$HOME/.config/hypr"
  if [[ -L "$hypr_dir" ]] && [[ "$(readlink -f "$hypr_dir" || true)" == "$active_dir" ]]; then
    echo "Symlink already points to $active_dir"
  else
    backup_existing_path "$hypr_dir"
    ln -s "$active_dir" "$hypr_dir"
    echo "Linked $hypr_dir -> $active_dir"
  fi
fi

if [[ $install_guard -eq 1 ]]; then
  install_systemd_guard
  echo "Installed and enabled $guard_path_name"
fi

if [[ $configure_faillock -eq 1 ]]; then
  if install_faillock_config; then
    echo "Configured PAM faillock for Hyprlock"
  else
    echo "Skipped PAM faillock config; rerun this script from a terminal if sudo needs a password" >&2
  fi
fi
